---
- name: Symlinking dotfiles
  file: src=~/github/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .gitconfig
    - .vimrc
    - .zlogin
    - .zlogout
    - .zpreztorc
    - .zprofile
    - .zshenv
    - .zshrc
