---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Add Brew Cask Tap
  action: shell brew tap caskroom/cask

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - ansible
    - ant
    - autoconf
    - automake
    - boot2docker
    - brew-cask
    - curl
    - git
    - gnu-sed
    - gradle
    - ivy
    - maven
    - openssl
    - postgresql
    - reattach-to-user-namespace
    - sqlite
    - tmux
    - tomcat
    - tree
    - unrar
    - vim
    - wget
    - zsh
    - zsh-completions

- name: Tap into the Homebrew Cask Beta apps
  homebrew_tap: tap=caskroom/versions state=present

- name: Install libraries with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - dropbox
    - eclipse-ide
    - firefox
    - google-chrome
    - intellij-idea
    - iterm2
    - skitch
    - transmission
    - virtualbox
    - vagrant
    - vagrant-manager
