---
- name: Enabling full keyboard access for all controls (e.g. enable Tab in modal dialogs)
  command: defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

- name: Enabling the 2D dock
  command: defaults write com.apple.dock no-glass -bool true

- name: Automatically hide and show the dock
  command: defaults write com.apple.dock autohide -bool true

- name: Making dock icons of hidden applications translucent
  command: defaults write com.apple.dock showhidden -bool true

- name: Allowing quit command in Finder via ⌘ + Q
  command: defaults write com.apple.finder QuitMenuItem -bool true

- name: Disabling window animations and Get Info animations in Finder
  command: defaults write com.apple.finder DisableAllAnimations -bool true

- name: Showing all filename extensions in Finder
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: Using current directory as default search scope in Finder
  command: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

- name: Expanding save panel by default
  command: defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

- name: Disabling press-and-hold for keys in favor of key repeat
  command: defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

- name: Setting a blazingly fast keyboard repeat rate
  command: defaults write NSGlobalDomain KeyRepeat -int 0.02

- name: Setting a shorter Delay until key repeat
  command: defaults write NSGlobalDomain InitialKeyRepeat -int 12

- name: Enabling AirDrop over Ethernet and on unsupported Macs running Lion
  command: defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

- name: Avoiding creating .DS_Store files on network volumes
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: Requiring password immediately after sleep or screen saver begins - Part I
  command: defaults write com.apple.screensaver askForPassword -int 1

- name: Requiring password immediately after sleep or screen saver begins - Part II
  command: defaults write com.apple.screensaver askForPasswordDelay -int 0

- name: Enabling tap to click (Trackpad) - Part I
  command: defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

- name: Enabling tap to click (Trackpad) - Part II
  command: defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

- name: Enabling tap to click (Trackpad) - PART III
  command: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

- name: Enabling Fn keys
  command: defaults write -g com.apple.keyboard.fnState -boolean true

- name: Changing computer name
  command: scutil --set HostName duck-of-doom
