---
- name: Installing RVM
  action: shell curl -sSL https://get.rvm.io | bash -s stable

- name: Installing Ruby
  action: shell rvm install ruby-2.2.0

- name: Setting new Ruby as system default
  action: shell rvm use --default ruby-2.2.0

- name: Setting gem source as rubygems.org
  action: shell gem source --add https://rubygems.org

- name: Updating system gems
  action: shell gem update --system

- name: Installing useful gems
  action: shell gem install {{ item }}
  with_items:
    - jekyll
    - pg
    - pry
    - rack
    - rake
    - rspec
    - sinatra
    - sqlite3
    - thor
    - unicorn
