- hosts: 127.0.0.1
  connection: local

  vars:
    applications:
      - iterm2
      - google-chrome
      - qlcolorcode 
      - qlstephen 
      - qlmarkdown 
      - quicklook-json 
      - qlprettypatch 
      - quicklook-csv 
      - betterzipql 
      - suspicious-package
      - mono-mdk
      - mono-mre
      - xamarin-studio
      - alfred
      - keyremap4macbook
      - pckeyboardhack
      - transmission

    libraries:
      - git
      - curl
      - wget
      - vim
      - tmux
      - zsh
      - reattach-to-user-namespace

  tasks:
    - name: Add cask cask homebrew tap
      shell: brew tap phinze/cask

    - name: Update package list
      shell: brew update

    - name: Install cask
      shell: brew install brew-cask

    - name: Check for installed applications (brew cask)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: false

    - name: Install applications (brew cask)
      shell: brew cask install {{ item }}
      with_items: applications
      when: "item not in installed_applications.results | map(attribute='stdout')"

    - name: Check for installed libraries (brew)
      shell: brew list | grep {{ item }}
      register: installed_libraries
      with_items: libraries
      ignore_errors: false

    - name: Install libraries (brew)
      shell: brew install --HEAD {{ item }}
      with_items: libraries
      when: "item not in installed_libraries.results | map(attribute='stdout')" 
